version: '3'

services:
  postgresql:
    image: postgres:11
    environment:
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "PostGr3s2021"
        PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
        - 54320:5432

  psql-admin:
    image: dockage/phppgadmin
    environment:
        PHP_PG_ADMIN_SERVER_HOST: "postgresql"
        PHP_PG_ADMIN_SERVER_PORT: "5432"
        PHP_PG_ADMIN_DEFAULT_LANG: "english"
    ports:
        - 50080:80